# CLASS 1
# Machine Learning Package - Part II

## Exercise 1 — NumPy array Indexing/Slicing (iris dataset)

In [1]:
import os
from pathlib import Path

import numpy as np

from si.io.csv_file import read_csv

if Path.cwd().name == 'scripts':
    os.chdir(Path.cwd().parent)

print(os.getcwd())

/Users/joanavilaca/sib


### 1.1) Load the iris dataset.

In [2]:
iris = read_csv('datasets/iris/iris.csv', 
                 sep      = ',', 
                 features = True, 
                 label    = True)

print(iris.X.shape)
print(iris.features)
print(iris.label)

(150, 4)
['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
class


### 1.2) Select the penultimate independent variable.
**What is the dimension of the resulting array?**

In [3]:
penultimate_feature = iris.X[:, -2]
print(penultimate_feature)
print('Shape:', penultimate_feature.shape)

[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]
Shape: (150,)


### 1.3) Select the last 10 samples from the iris dataset.
**What is the mean of the last 10 samples for each independent variable?**

In [4]:
last_10_samples = iris.X[-10:]
print(last_10_samples)

mean_last_10 = last_10_samples.mean(axis = 0)
print('Mean of last 10 samples per feature:', mean_last_10)

[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
Mean of last 10 samples per feature: [6.45 3.03 5.33 2.17]


### 1.4) Select all samples with values <= 6 for all independent variables.
**How many samples do you obtain?**

In [5]:
mask = np.all(iris.X <= 6, axis = 1)
samples_leq_6 = iris.X[mask]
print('Number of samples:', samples_leq_6.shape[0])

Number of samples: 89


### 1.5) Select all samples with a class/label different from 'Iris-setosa'.
**How many samples do you obtain?**

In [6]:
mask_not_setosa = iris.y != 'Iris-setosa'
samples_not_setosa = iris.X[mask_not_setosa]
print('Number of samples:', samples_not_setosa.shape[0])

Number of samples: 100


## Exercise 2 — NumPy array Indexing/Slicing 
### 2.1) dropna.
**Load a version of the dataset that has missing values, then remove every sample containing at least one NaN.**

In [7]:
iris_missing = read_csv('datasets/iris/iris_missing_data.csv', 
                        sep      = ',', 
                        features = True, 
                        label    = True)

print('Shape before dropna:', iris_missing.X.shape)

iris_missing.dropna()
print('Shape after dropna:', iris_missing.X.shape)

Shape before dropna: (150, 4)
Shape after dropna: (134, 4)


### 2.2) fillna
**Load the dataset with missing values again and replace the NaNs with a fixed value, the mean, or the median of each feature.**

In [8]:
iris_missing_fixed = read_csv('datasets/iris/iris_missing_data.csv', 
                              sep      = ',', 
                              features = True, 
                              label    = True)

iris_missing_fixed.fillna(0.0)
print('Any NaN left (fillna with 0.0)?', np.isnan(iris_missing_fixed.X).any())

iris_missing_mean = read_csv('datasets/iris/iris_missing_data.csv', 
                             sep      = ',', 
                             features = True, 
                             label    = True)

iris_missing_mean.fillna('mean')
print('Any NaN left (fillna with mean)?', np.isnan(iris_missing_mean.X).any())

iris_missing_median = read_csv('datasets/iris/iris_missing_data.csv',
                               sep      = ',', 
                               features = True, 
                               label    = True)

iris_missing_median.fillna('median')
print('Any NaN left (fillna with median)?', np.isnan(iris_missing_median.X).any())

Any NaN left (fillna with 0.0)? False
Any NaN left (fillna with mean)? False
Any NaN left (fillna with median)? False


### 2.3) remove_by_index
**Remove a single sample by its index.**

In [9]:
iris_copy = read_csv('datasets/iris/iris.csv', 
                     sep      = ',', 
                     features = True, 
                     label    = True)

print('Shape before removal:', iris_copy.X.shape)

iris_copy.remove_by_index(0)
print('Shape after removing sample 0:', iris_copy.X.shape)

Shape before removal: (150, 4)
Shape after removing sample 0: (149, 4)


## Exercise 3 — Implementing and testing SelectPercentile
### 3.3) Test the SelectPercentile class using the iris dataset (classification).

In [10]:
from si.feature_selection.select_percentile import SelectPercentile

**Load the iris dataset.**

In [11]:
iris_fs = read_csv('datasets/iris/iris.csv',
                    sep      = ',', 
                    features = True, 
                    label    = True)

print('Original shape:', iris_fs.X.shape)
print('Features:', iris_fs.features)

Original shape: (150, 4)
Features: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']


**Fit SelectPercentile and inspect the F and p values.**

In [12]:
selector = SelectPercentile(percentile = 50)
selector.fit(iris_fs)

print('F values:', selector.F)
print('p values:', selector.p)

F values: [ 119.26450218   47.3644614  1179.0343277   959.32440573]
p values: [1.66966919e-31 1.32791652e-16 3.05197580e-91 4.37695696e-85]


**Transform the dataset (keep the top 50% most discriminative features).**

In [13]:
iris_fs_selected = selector.transform(iris_fs)

print('New shape:', iris_fs_selected.X.shape)
print('Selected features:', iris_fs_selected.features)

New shape: (150, 2)
Selected features: ['petal_length', 'petal_width']


**Try a different percentile.**

In [14]:
selector_25 = SelectPercentile(percentile = 25)
iris_fs_selected_25 = selector_25.fit_transform(iris_fs)

print('Shape with percentile = 25:', iris_fs_selected_25.X.shape)
print('Selected features:', iris_fs_selected_25.features)

Shape with percentile = 25: (150, 1)
Selected features: ['petal_length']


## Exercise 6 — Implementing stratified splitting
### 6.2) Test the stratified_train_test_split function (iris dataset).

In [15]:
from si.model_selection.split import stratified_train_test_split

**Load the iris dataset**

In [16]:
iris_split = read_csv('datasets/iris/iris.csv', 
                      sep      = ',', 
                      features = True, 
                      label    = True)

print('Original shape:', iris_split.X.shape)

Original shape: (150, 4)


**Split the dataset (20% test).**

In [17]:
train, test = stratified_train_test_split(iris_split, 
                                          test_size    = 0.2, 
                                          random_state = 42)

print('Train shape:', train.X.shape)
print('Test shape: ', test.X.shape)

Train shape: (120, 4)
Test shape:  (30, 4)


**Check that the class proportions are preserved.**

In [18]:
def class_proportions(dataset):
    classes, counts = np.unique(dataset.y, return_counts = True)
    for c, n in zip(classes, counts):
        print(f'  {c:<16} {n:>3}  ({n / counts.sum():.2%})')

print('Original:')
class_proportions(iris_split)
print('Train:')
class_proportions(train)
print('Test:')
class_proportions(test)

Original:
  Iris-setosa       50  (33.33%)
  Iris-versicolor   50  (33.33%)
  Iris-virginica    50  (33.33%)
Train:
  Iris-setosa       40  (33.33%)
  Iris-versicolor   40  (33.33%)
  Iris-virginica    40  (33.33%)
Test:
  Iris-setosa       10  (33.33%)
  Iris-versicolor   10  (33.33%)
  Iris-virginica    10  (33.33%)


## Exercise 7 — Implementing the KNNRegressor with RMSE
### 7.3) Test the KNNRegressor class using the cpu dataset (regression)

In [19]:
from si.models.knn_regressor import KNNRegressor
from si.model_selection.split import train_test_split

**Load the cpu dataset.**

In [20]:
cpu = read_csv('datasets/cpu/cpu.csv', 
               sep      = ',', 
               features = True, 
               label    = True)

print('Shape:',    cpu.X.shape)
print('Features:', cpu.features)
print('Label:',    cpu.label)

Shape: (209, 6)
Features: ['syct', 'mmin', 'mmax', 'cach', 'chmin', 'chmax']
Label: perf


**Split the dataset (20% test).**

In [21]:
cpu_train, cpu_test = train_test_split(cpu, 
                                       test_size    = 0.2, 
                                       random_state = 42)

print('Train shape:', cpu_train.X.shape)
print('Test shape: ', cpu_test.X.shape)

Train shape: (168, 6)
Test shape:  (41, 6)


**Fit the KNNRegressor and compute the RMSE on the test set.**

In [22]:
knn_reg = KNNRegressor(k = 3)
knn_reg.fit(cpu_train)

score = knn_reg.score(cpu_test)
print(f'RMSE (k = 3): {score:.2f}')

RMSE (k = 3): 81.36
